name = "DifferentiableMoM"
uuid = "23e8cd96-b521-4dc5-8732-25c09bc9e688"
license = "MIT"
version = "0.1.0"
authors = ["Jake W. Liu <jwliu@ntut.edu.tw>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlotlyKaleido = "f2990250-8cf9-495f-b13a-cce12b45703c"
PlotlySupply = "a389b534-8bca-4fe3-8ff2-14829cd8824f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CSV = "0.10"
DataFrames = "1"
JSON = "1"
Krylov = "0.9"
PlotlyKaleido = "2.3.1"
PlotlySupply = "1.4.0"
StaticArrays = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
